config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :toothbrushes, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :destroy, :validate] do
      collection do
        get 'validate'
        get 'decline'
        get 'cancel'
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :toothbrush
end

app/models/toothbrush.rb
class Toothbrush < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :delete_all
  validates :title, :description, :photo, :price, :brand, presence: true
  validates :title, length: { minimum: 4 }
  validates :description, length: { minimum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :toothbrushes, dependent: :delete_all
  has_many :bookings, dependent: :delete_all
  
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :num_notif

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :photo_url, :photo])
  end

  def num_notif
    if user_signed_in?
    @bookings_owner = Booking.joins(:toothbrush).where(toothbrushes: { user_id: current_user.id })
    @pending_requests = @bookings_owner.where(status:"⏳ pending" )
    @notif_number = @pending_requests.count
    end
  end

  #   bookings = Booking.where(status: "⏳ pending")
  #   user_occurence = []
  #   bookings.each do |booking|
  #     if booking.toothbrush.user == current_user
  #       user_occurence << toothbrush
  #     end
  #   end
  #   @notif_number = user_occurence.count
  # end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user.id)
    @bookings_owner = Booking.joins(:toothbrush).where(toothbrushes: { user_id: current_user.id })
  end

  def new
    @booking = Booking.new
    @toothbrush = Toothbrush.find(params[:toothbrush_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @toothbrush = Toothbrush.find(params[:toothbrush_id])
    @booking.toothbrush = @toothbrush
    @booking.save!
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  def validate
    @booking = Booking.find(params[:format])
    @booking.status = "✔️ confirmed"
    @booking.save!
    redirect_to bookings_path
  end

  def decline
    @booking = Booking.find(params[:format])
    @booking.status = "⤫ declined"
    @booking.save!
    redirect_to bookings_path
  end

  def cancel
    @booking = Booking.find(params[:format])
    @booking.status = "⤫ cancelled"
    @booking.save!
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @toothbrushes_list = Toothbrush.all
    @toothbrushes = Toothbrush.all.last(3).reverse
    @user = current_user
    @vintage = Toothbrush.where(category: "Vintage")

    # For map
    @users_list = User.all
    @markers = @users_list.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        info_window: render_to_string(partial: "info_window", locals: { user: user }),
        image_url: helpers.asset_url('https://res.cloudinary.com/dg2an4buq/image/upload/v1637929695/pngkit_tooth-brush-png_809504_vsi4jl.png')
      }
    end
  end

  private

  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :address, :email, :password, :photo_url, :photo)
  end

end

app/controllers/toothbrushes_controller.rb
class ToothbrushesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index


  def index
    if params[:category].present?
      @toothbrushes = Toothbrush.where(category: params[:category].capitalize)
    else
      @toothbrushes = Toothbrush.all
    end
  end

  def show
    @toothbrush = Toothbrush.find(params[:id])
    @user = User.find(@toothbrush.user_id)
    @booking = Booking.new
    @user_owner = User.find(@toothbrush.user_id)

    # For map
    @markers = [{ lat: @user.latitude, lng: @user.longitude }]

  end

  def new
    @toothbrush = Toothbrush.new
  end

  def create
    @toothbrush = Toothbrush.new(toothbrush_params)
    @toothbrush.user = current_user

    @toothbrush.save
    if @toothbrush.save
      redirect_to toothbrush_path(@toothbrush)
    else
      render :new
    end

  end

  def edit
    @toothbrush = Toothbrush.find(params[:id])
  end

  def update
    @toothbrush = Toothbrush.find(params[:id])
    @toothbrush.update(toothbrush_params)
    if @toothbrush.update(toothbrush_params)
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @toothbrush = Toothbrush.find(params[:id])
    @toothbrush.destroy
    redirect_to user_path(current_user)
  end

  private

  def toothbrush_params
    params.require(:toothbrush).permit(:title, :description, :condition, :price, :brand, :category_id, :user_id, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @toothbrushes = Toothbrush.where(user: current_user)
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<!--<body <%= "data-no-turbolinks='true'".html_safe if controller_name=="pages" && action_name=="policy" %>>-->
<div class="banner banner-pages" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://as1.ftcdn.net/v2/jpg/02/54/15/88/1000_F_254158873_4o1cACXKRRtIaEYEcI1HP2V9F0mzQlRK.jpg);">
  <div class="container">
    <h1>All your <strong>Bookings</strong></h1>
    <p>Wow you are such a great user!</p>
  </div>
</div>


<div class="container my-button d-flex align-items-center">
  <button class='my-custom-button' id='btn-customer'>Customer</button>
  <button class='my-custom-button change-button' id='btn-owner'>Owner</button>
  <% if @notif_number > 0 %>
    <span class="badge badge-pill badge-danger badge-position"><%= @notif_number %></span>
  <% end %>
</div>

<div class='container' id='booking-sent'>
  <h2>Booking sent</h2>
  <p>You will find below the list of all the renting request you sent.</p>
  <div class="column">
    <% @bookings.each do |booking|%>
      <% booking_length = booking.end_date - booking.start_date %>
      <div class="card text-center d-flex flex-row mb-2" style='height: 100%px'>
        <%=cl_image_tag booking.toothbrush.photo.key, style:" height: 100%px; width: 260px; crop:cover"%>
        <p class="card-text card-status"> <%= booking.status%></p>
        <div class="card-body d-flex-row justify-content-between">
        <h3 class="card-title">Request sent to: <%= booking.toothbrush.user.first_name %></h3>
          <p class="card-text">Booking ref: <%= booking.id %></p>
          <div class="d-flex flex-wrap">
            <p class="card-text" style="width: 50%"><span class="color-orange">Start date</span> <%= booking.start_date %></p>
            <p class="card-text" style="width: 50%"><span class="color-orange">End date</span> <%= booking.end_date %></p>
            <p class="card-text" style="width: 50%"><span class="color-orange">Booking lenght</span> <%= booking_length.to_i + 1 %> day(s)</p>
            <p class="card-text" style="width: 50%"><span class="color-orange">Total price</span> <%= (booking_length.to_i + 1) * booking.toothbrush.price.to_i %> CHF</p>
          </div>
          <% if booking.status == "⤫ cancelled" %>
              <p class='bg-light mb-0'>Your already <strong>cancelled</strong> this request.</p>
          <% elsif booking.status == "⤫ declined" %>
              <p class='bg-light mb-0'>The owner <strong>declined</strong> your request.</p>
          <% else %>
            <%= link_to "Cancel request",cancel_bookings_path(booking), class:'btn btn-warning' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class='container hidden' id='booking-received'>
  <h2>Booking requests received</h2>
  <p>You found customer for your toothburshes. Here is the list of all the requests you received. You can now confirm or decline them!</p>
  <div class="column">
    <% @bookings_owner.each do |booking|%>
      <% booking_length = booking.end_date - booking.start_date %>
      <div class="card text-center d-flex flex-row mb-2" style='height: auto'>
        <%=cl_image_tag booking.toothbrush.photo.key, style:" height: 100%px; width: 260px; crop:cover"%>
        <p class="card-text card-status"><%= booking.status %></p>
        <div class="card-body d-flex-row justify-content-between">
          <h3 class="card-title">Booking by: <%= booking.user.first_name %></h3>
          <p class="card-text">Booking ref: <%= booking.id %></p>
          <div class="d-flex flex-wrap">
            <p class="card-text" style="width: 50%"><span class="color-orange">Start date</span> <%= booking.start_date %></p>
            <p class="card-text" style="width: 50%"><span class="color-orange">End date</span> <%= booking.end_date %></p>
            <p class="card-text" style="width: 50%"><span class="color-orange">Booking lenght</span> <%= booking_length.to_i + 1 %> day(s)</p>
            <p class="card-text" style="width: 50%"><span class="color-orange">Your revenue</span> <%= (booking_length.to_i + 1) * booking.toothbrush.price.to_i %> CHF</p>
          </div>
          <% if booking.status =='⏳ pending' %>
            <%= link_to "Accept",validate_bookings_path(booking), class:'btn btn-success' %>
            <%= link_to "Decline",decline_bookings_path(booking), class:'btn btn-danger' %>
          <% elsif booking.status =='✔️ confirmed' %>
            <%= link_to "Decline*",decline_bookings_path(booking), class:'btn btn-danger' %>
          <% else %>
            <p class='bg-light'>Your already <strong>declined</strong> this request.</p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <p class="text-secondary">* declining a booking you already confirmed will generate cancelation fee</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareMyToothbrush</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <!--For map-->
    <%= stylesheet_pack_tag 'application' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/_info_window.html.erb
<p><%= user.first_name%> <%=user.last_name %></p>
<img class="card-list-user avatar-bordered" src="http://res.cloudinary.com/dg2an4buq/image/upload/v1/development/o38elsq3x5t4vzsb6r9wzruza6g5">
<p><%= user.address %></p>
<div>
<a class="btn btn-primary btn-rounded btn-soso mt-5">Book now</a>
</div>

app/views/pages/home.html.erb
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://as1.ftcdn.net/v2/jpg/02/54/15/88/1000_F_254158873_4o1cACXKRRtIaEYEcI1HP2V9F0mzQlRK.jpg);height:80vh;">
    <div class="container">
      <h1>Share my <strong>toothbrush</strong></h1>
      <p>Find the right toothbrush you need around the world, or rent yours to earn money!</p>
      <a class="btn btn-primary btn-home btn-soso" href="#">Be eco-friendly, share your toothbrush!</a>
    </div>
  </div>

<div class="container">
  <!--template responsive une fois rempli avec contenu desiré juste mettre 100vh est c'est tout bon :) normalement... -->
  <div class="container container-superpose">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="icon-home">
          <%= image_tag "https://res.cloudinary.com/dg2an4buq/image/upload/v1637763512/ecology_bzbye7.png", alt: "", width: 120 %>
          <h2>Eco-Friendly</h2>
          <p>Use someone else's toothbrush instead of buying a new one, and make something good for our planet earth.</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="icon-home">
          <%= image_tag "https://res.cloudinary.com/dg2an4buq/image/upload/v1637763512/icon-bacteria_zhvgk1.png", alt: "", width: 120 %>
          <h2>Collective Immunity</h2>
          <p>Rent your toothbrush: share your saliva and bacteria with your new buddy. Let his immune system grows and becomes stronger!</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="icon-home">
          <%= image_tag "https://res.cloudinary.com/dg2an4buq/image/upload/v1637763512/nettoyage-dent_trfhnj.png", alt: "", width: 120 %>
          <h2> Select your type</h2>
          <p>Choose a soft one when you have sensitives gums, or an electric one when you need a deep complete cleaning before meeting your next Tinder's date.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="container container-text">
    <p>Welcome to ShareMyToothBrush.com! On this plateform you can easily rent your toothbrush, or find the perfect one for you, for a determined period!
    Find the toothbrush you need, wherever you need it! Choose between differents categories, status or prices, near your actual position.
    Use it for a day or more, and then bring it back to his owner. Test as many as toothbrushes you want, without buying anything, just renting!
    <br>Enjoy!</p>
  </div>

  <div class="container-center" style="margin:40px 0;text-align:center"><a href="/toothbrushes/new" class="btn btn-home btn-primary btn-soso">Post an add and share your toothbrush!</a></div>

  <h2 class="title-homepage">Newest listings</h2>
  <div class="row container-flex">
    <% @toothbrushes.each do |toothbrush|%>
      <div class="card-list">
        <%=cl_image_tag toothbrush.photo.key, crop: :fill%>
        <div class="card-list-infos">
          <div>
            <h2><%= toothbrush.title %></h2>
            <p><%= toothbrush.condition %></p>
            <p><%= link_to "See more", toothbrush_path(toothbrush) %></p>
          </div>
          <h2 class="card-list-pricing"><%= toothbrush.price %> CHF/day</h2>
          <%=cl_image_tag toothbrush.user.photo.key, class:"card-list-user avatar-bordered"%>
        </div>
      </div>
    <%end%>
  </div>

  <div class="best-category">
    <h2>Best categories</h2>
    <div style="display:flex;justify-content:space-around;margin-bottom:50px">
      <div class="card-category card-cat-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://as2.ftcdn.net/v2/jpg/03/98/34/83/1000_F_398348308_yUCYBw6T7RYX4yTAMGee9fWdLCKbHYW5.jpg)">
        <%=link_to 'Famous', toothbrushes_path(category: "famous")%> </div>
      <div class="card-category card-cat-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://as1.ftcdn.net/v2/jpg/00/00/43/68/1000_F_436857_Vm9o6Gq0oTlZsoTYDA6734EgymR1XT.jpg)">
        <%= link_to "Vintage", toothbrushes_path(category: "vintage") %></div>
      <div class="card-category card-cat-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://as1.ftcdn.net/v2/jpg/02/55/71/04/1000_F_255710484_K62V2GwfP4OxmJNHo9KRUIyDAM4h4QNF.jpg)">
        <%=link_to 'Plastic', toothbrushes_path(category: "Plastic")%></div>
    </div>
  </div>
  <!--For map-->


  <div class="mb-3"id="map"
    style="width: 100%; height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
  <p>Share your toothbrush with other people near to you </p>
  </div>
  <div class="footer-copyright">
    This footer is made with so much <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dg2an4buq/image/upload/v1637763512/logo-toothbrush_x84yiz.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Available Tootbrushes", "/toothbrushes", class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to "🪥Rent your toothbrush", "/toothbrushes/new", class: "btn btn-primary btn-home btn-soso" %>
        </li>
          <li class="nav-item dropdown">
            <%=cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
            <% if @notif_number > 0 %>
              <span class="badge badge-pill badge-danger badge-position"><%= @notif_number %></span>
            <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My bookings (#{@notif_number})", bookings_path, class: "dropdown-item" %>
            <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/toothbrushes/edit.html.erb
<div class="banner banner-pages" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://as1.ftcdn.net/v2/jpg/02/54/15/88/1000_F_254158873_4o1cACXKRRtIaEYEcI1HP2V9F0mzQlRK.jpg);">
  <div class="container">
    <h1>Edit your <strong>toothbrush</strong></h1>
  </div>
</div>
<div class='container container-new-form'>
  <div class="form-container">
    <%= simple_form_for @toothbrush do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :brand %>
      <%= f.input :condition, :collection => ["New", "Used", "Bad", "End of life"]%>
      <%= f.input :category, :collection => ["Eco-friendly", "Plastic", "Vintage", "Famous", "Electric"]%>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Update", class: "btn btn-primary btn-home" %>
    <% end %>
  </div>
</div>

app/views/toothbrushes/index.html.erb
<div class="banner banner-pages" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://as1.ftcdn.net/v2/jpg/02/54/15/88/1000_F_254158873_4o1cACXKRRtIaEYEcI1HP2V9F0mzQlRK.jpg);">
  <div class="container">
    <h1>Choose your <strong>toothbrush</strong></h1>
    <p>Find the right toothbrush for your teeths in the list below!</p>
  </div>
</div>

<h2 class='pl-4'>All available toothbrushes</h2>
<div class="row container-flex">
  <% @toothbrushes.each do |toothbrush|%>
    <div class="card-list" style="margin-top:20px ">
      <%=cl_image_tag toothbrush.photo.key, crop: :fill%>
      <div class="card-list-infos">
        <div>
          <h2><%= toothbrush.title %></h2>
          <p><%= toothbrush.condition %></p>
          <p><%= link_to "See more", toothbrush_path(toothbrush)%></p>
        </div>
        <h2 class="card-list-pricing"><%= toothbrush.price %> CHF/day</h2>
         <%=cl_image_tag toothbrush.user.photo.key, class:"card-list-user avatar-bordered"%>
      </div>
    </div>
  <%end%>
</div>

<div class="container-center" style="margin:40px 0;text-align:center"><a href="/toothbrushes/new" class="btn btn-home btn-primary btn-soso">Post an add and share your toothbrush!</a></div>

app/views/toothbrushes/new.html.erb
<div class="banner banner-pages" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://as1.ftcdn.net/v2/jpg/02/54/15/88/1000_F_254158873_4o1cACXKRRtIaEYEcI1HP2V9F0mzQlRK.jpg);">
  <div class="container">
    <h1>Add a new<strong>toothbrush</strong></h1>
    <p>Fill the form and find someone to rent your toothbrush!</p>
  </div>
</div>
<div class='container container-new-form'>
  <div class="form-container">
    <%= simple_form_for @toothbrush do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :brand %>
      <%= f.input :condition, :collection => ["Hard", "Medium", "Soft"]%>
      <%= f.input :category, :collection => ["Eco", "Wood", "Electric", "Plastic", "Metal"]%>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Submit review", class: "btn btn-primary btn-home" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="banner banner-pages" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://as1.ftcdn.net/v2/jpg/02/54/15/88/1000_F_254158873_4o1cACXKRRtIaEYEcI1HP2V9F0mzQlRK.jpg);">
  <div class="container">
    <h1>Edit your <strong>Informations</strong></h1>
  </div>
</div>
<div class='container container-new-form'>
  <div class="form-container">
    <%= simple_form_for @user do |f| %>
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :address %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Update", class: "btn btn-primary btn-home" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3">

  <h3>Your profile</h3>
  <br>

  <div id="user-data">

    <div class="mb-1 py-3 card card-body flex-row justify-content-between col-md-10" id="user-info">
      <div class="d-flex flex-column" style="max-width: 65%">
        <h5><%= @user.first_name.capitalize %> <strong><%= @user.last_name.upcase %></strong></h5>
        <p class="mb-0">Address: <%= @user.address %></p>
      </div>
      <div>
        <%= link_to "✍️ Update your infos", edit_user_path, style:"width: 30%" %></p>
      </div>
    </div>

    <div class="mb-1 py-3 card card-body flex-row justify-content-between col-md-10" id="user-login">
      <div class="d-flex flex-column" style="max-width: 65%">
        <p>Account email: <%= @user.email %></p>
        <p class="mb-0"> Password: ************ </p>
      </div>
      <div>
        <%= link_to "🔐 Change your password", edit_user_registration_path, style:"width: 30%" %>
      </div>
    </div>
    <br>
    <hr size="1" width="83.3%" color="#6c757d">
  </div>


  <% if @toothbrushes.present? %>
    <br>
    <h3>My Toothbrushes</h3>
    <br>

    <div class ="mb-3" id="owned-tb-list">
      <% @toothbrushes.each do |toothbrush| %>
        <div class="col-md-10 align-items-stretch p-0">
          <div class="card flex-row" style="overflow:hidden">
            <%=cl_image_tag toothbrush.photo.key, class:"img-fluid", style:"max-width: 35%", crop: :fill%>
            <div class="card-body d-flex flex-column">
              <h4 class=""><%= toothbrush.title %></h4>
              <p><span class="color-orange">Current price: </span> <%= toothbrush.price %> CHF/day</p>
              <p><span class="color-orange">Condition: </span> <%= toothbrush.condition %></p>
              <p style="margin-bottom: 0px"><span class="color-orange">Brand: </span> <%= toothbrush.brand %></p>
              <div class="d-flex justify-content-end" style="width=100%">
                <button class="btn btn-outline-secondary" style="margin-right: 10px"> <%= link_to "Modify", edit_toothbrush_path(toothbrush), style:"color:#6c757d " %> </button>
                <button class="btn btn-outline-danger">
                  <%= link_to "Delete",
                    toothbrush_path(toothbrush),
                    method: :delete,
                    data: { confirm: "Are you sure?" },
                  style:"color:#FD1015" %> </button>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="col-md-10 text-center mb-3">
      <br>
      <h3 class="mb-4">You don't have any toothbrush available</h3>
      <h5 class="mb-4">Make yours available today!</h5>
      <%= link_to "🪥 Add yours today", new_toothbrush_path, class:"btn btn-primary mb-4" %>
      <br>
    </div>
  <% end %>

</div>